import Head from "next/head";
import { TableProvider } from "../providers/indexContext";
import MyTable from "../components/MyTable";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TableProvider>
          <MyTable />
        </TableProvider>
      </main>
    </div>
  );
};

export default Home;
